[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pt/MgO"
authors = [{name = "Trevor Price", email = "tdprice@ucdavis.edu"}]
dynamic = ["version", "description"]
